- app/models/booking.rb
- app/models/car.rb
- app/models/user.rb
Added model validations as a group.
> Validations for each model added.

- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_show.scss
- app/controllers/cars_controller.rb
- app/models/car.rb
- app/views/cars/show.html.erb
- app/views/devise/registrations/new.html.erb
- db/migrate/20200224192236_change_type_column_name_in_cars.rb
- db/schema.rb
- Fixed signup form to match the validations for first_name and last_name
- Fixed validations typo
- Renamed the type column to kind to prevent the Ruby method conflict with .type
- Lightweight view for show
> Testing for tomorrow

- Gemfile
- Gemfile.lock
- db/seeds.rb
seed file created to populate the database with cars.
Please check all the attributes, especially price attribute and agree price.sample or price random.
see code: 
price: price.sample # or price: rand(1..100)
> Seed database

- db/seeds.rb
Debugged the seed file
price to rand instead of sample
> debugged seed file

- app/assets/stylesheets/pages/_show.scss
- app/views/cars/show.html.erb
until we change the model to allow for a description.
> Added book button and hard-coded a paragraph in the description

- app/controllers/cars_controller.rb
- app/controllers/pages_controller.rb
- app/views/cars/index.html.erb
Made changes to home page (allowed login for non-registered user)
Created index action for home page
Raw showcase of cars on index page
> Login change home

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/cars_controller.rb
- app/controllers/pages_controller.rb
- app/policies/application_policy.rb
- app/policies/car_policy.rb
- test/policies/car_policy_test.rb
I added the 'pundit' gem
added pundit to our app
- installed pundit table
- created and modified car policy
- changed cars_controller
- added pundit to application controller
> Add pundit to our project

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_navbar.scss
- app/controllers/cars_controller.rb
- app/views/shared/_navbar.html.erb
-Added a search bar in the navbar (_navbar.html.erb)
-Changed the index method for cars controller in order to be able to search
-added css styling to _button.scss in order to style buttons
> Search method navbar

- app/controllers/application_controller.rb
I solved the signup which was not working anymore: 
it was because I commented third line in application controller during setting up pundit
> resolved signup not working

- app/controllers/cars_controller.rb
- app/policies/car_policy.rb
search bar in the navbar now works for searching a brand of a car
> search bar for searching brand works

- app/assets/stylesheets/pages/_show.scss
- app/controllers/bookings_controller.rb
- app/controllers/cars_controller.rb
- app/models/booking.rb
- app/policies/booking_policy.rb
- app/views/bookings/_form.html.erb
- app/views/bookings/show.html.erb
- app/views/cars/show.html.erb
- test/policies/booking_policy_test.rb
- Put a skeleton version of bookings in place
- Added validation for date (cannot be in the past)
- Setup Pundit for bookings.
> Create booking view

- app/assets/stylesheets/components/_navbar.scss
- app/views/shared/_navbar.html.erb
> styling on search form done

- app/assets/stylesheets/components/_button.scss
- deleted unnecessary styling inside button component
> modified components button

- app/models/booking.rb
- Added validation preventing end date from being earlier than start date.
> Update booking validation

- app/views/cars/index.html.erb
added another image instead of the lego (?) image
> small update on images index

- .gitignore
- Gemfile
- Gemfile.lock
- app/controllers/cars_controller.rb
- app/models/car.rb
- app/views/cars/_form.html.erb
- config/environments/development.rb
- config/environments/production.rb
- config/storage.yml
- db/migrate/20200227111531_create_active_storage_tables.active_storage.rb
- db/schema.rb
NO VISIBLE CHANGES YET
- Created cloudinary from the backend
- Nothing is visible in the frontend but I verified it worked manually.
- Next steps are to create the form and allow user image upload.
> Completed cloudinary for backend.

- app/controllers/cars_controller.rb
- app/models/car.rb
- app/models/user.rb
- app/policies/car_policy.rb
- app/views/cars/_form.html.erb
- app/views/cars/new.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
- db/migrate/20200227120649_add_user_ref_to_cars.rb
- db/schema.rb
- Routes are in place
- Pundit policies have been updated
- Image upload is inside the form
> Got the form and image upload working in the front end.

- app/models/car.rb
- app/views/cars/index.html.erb
- app/views/cars/show.html.erb
- Removed hard-coded images in show and index
- Added validation on image
> Clean up car image rendering

- app/views/bookings/index.html.erb
- app/views/bookings/show.html.erb
removed hard-coded pictures from bookings
> My bookings index + show

- app/assets/stylesheets/pages/_create_new_car.scss
- app/assets/stylesheets/pages/_index.scss
- app/views/shared/_navbar.html.erb
- Added margins and a scss file
> Refine car create form

- app/assets/stylesheets/components/_card.scss
- app/models/car.rb
- app/views/cars/index.html.erb
- app/views/layouts/application.html.erb
In the Car index page the cars are now separated by the kind of the cars
also changed title of the page in head
> Kind separation

- app/views/cars/index.html.erb
Changed price to price per day
> change price to price per day

- app/controllers/application_controller.rb
- app/models/user.rb
- app/views/devise/registrations/new.html.erb
- app/views/shared/_navbar.html.erb
Avatar photo is in place and working now. This will probably require you to create a new user to prevent a crash, since we require user photos now.
> Exp avatar photo

- app/controllers/cars_controller.rb
- app/views/cars/_form.html.erb
I added an array of kinds to the cars_controller#new
The user can only select now from this kinds
> Restrict kind selection

- app/views/bookings/index.html.erb
- app/views/bookings/show.html.erb
Changed the output dateformat for start_date and end_date in booking details and bookings index page
> Show better dateformat

- app/views/cars/index.html.erb
Can search cars again. The car kind grouping display on the index yesterday broke search.
> Fixed car search

- app/controllers/cars_controller.rb
- app/views/cars/_form.html.erb
added fixed types of drive_train. 
The user can select them with a dropdown
> added fixed drive_train_types

- app/views/bookings/index.html.erb
- app/views/bookings/show.html.erb
- app/views/cars/index.html.erb
- app/views/cars/show.html.erb
removed crop: :fill property from car image_tags
> moved crop fill property from car image_tag

- app/assets/stylesheets/pages/_carshow.scss
- app/views/cars/show.html.erb
- app/views/reviews/_show.html.erb
- app/views/reviews/create.js.erb
- Individual reviews have better separation now
- Review text has better padding
- Reviews will contain user avatars instead of names
> Tweaked style of review ui and added the reviewing user's avatar.

- app/javascript/plugins/flatpickr.js
Dates in flatpicker are now human readable
> Fixed dates for flatpicker to be more human readable.

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_review.scss
- app/assets/stylesheets/pages/_carshow.scss
- app/controllers/reviews_controller.rb
- app/views/bookings/_form.html.erb
- app/views/cars/show.html.erb
- app/views/reviews/_form.html.erb
- app/views/reviews/_show.html.erb
- db/migrate/20200228141933_add_rating_to_reviews.rb
- db/schema.rb
- added rating to reviews table
- added ratings to review create form
- added ratings to reviews in car show
- fixed date was saved wrong => price calculation works again correctly
- fixed user can see car details when not logged in and user can only book car others than his own
> Rating review
